// @version 5.0.816
(function(r,m,k,v,L,C,D,w,x,S,o,p,M,pa,ca,t,y,z,N,T,da,O,n){function U(a,b,d){if(!a)for(a in q)return q[a];var c=new ea(a);d&&c.va();return q[b||a]=c}function V(a){for(var b in q)q[T](b)&&a(q[b])}function qa(a,b){return function(){a.call(b)}}function A(a,b,d,c){var f;(f=a.addEventListener)?f.call(a,b,d,p):a.attachEvent(c||"on"+b,d)}function u(a,b){return function(){a(b)}}function F(a,b,d){if(!fa)if("function"==typeof a)a();else if(ra.test(a))"string"!=typeof b&&(d=b,b=0),U(a,b,d||d===n);else if(/^_/.test(a))P[a]&&
P[a](b,d),delete P[a];else{var a=a[t]("."),c;1<a[z]&&(c=a.shift());a=a[0];if("get"==a)return sa(c,b);"set"==a?Q(c,b,d):"track"==a?W(X,c,b,d):"event"==a?W(ga,c,b,d):"cancel"==a?ta(c):"noCookies"==a?Q(c,1,p):"anonymizeIP"==a?Q(c,2,o):"tag"==a?Q(c,3,b):"load"==a?b&&b():"implode"==a&&(fa=o)}}function Q(a,b,d){var c=ha[(b+"")[N]()]||b;a?q[a].o(c,d):V(function(a){a.o(c,d)})}function sa(a,b){var d=ha[(b+"")[N]()]||b,c;if(a)return q[a].b(d);V(function(a){c=a.b(d)});return c}function ia(a,b){function d(a){return"expires="+
(new D(a)).toGMTString()+";"}var c="path=/;",f=a.b(6);f&&(c+="domain="+f+";");return{J:function(e,f){a.b(1,o)&&(k.cookie=e+"="+f+";"+d(+new D+(b?6E10:6E4))+c)},m:function(b){if(a.b(1,o))return(k.cookie.match("(^|;)\\s*"+b+"=(.*?)(;|$)")||[])[2]||M},aa:function(a){k.cookie=a+"=;"+d(0)+c}}}function W(a,b,d,c){b?a.call(q[b],d,c):V(function(b){a.call(b,d,c)})}function ta(a){W(function(){this.v()},a)}function ea(a){var b=this;b.c=a;b.Da=p;var d=[];b.o=function(a,b){d[a]=b};b.b=function(a,b){return a in
d?d[a]:b};var c;b.va=function(){c=w(qa(X,b),b.b(9,200))};b.v=function(){x(b.g);x(c)}}function X(a,b){function d(a){j.cb=a}var c=this,f=ua(c,a,b),e=va(c),g=wa(c,!e.D,a!==n),i=xa(),h=ya(a),E=ja(),j,k=c.b(5);x(c.g);c.h=0;c.f=p;ka(c);if(!f.ea&&(!f.da&&!(v&&"preview"==v.loadPurpose))&&(!i.d.k||!i.d.j||!(10>i.d.k&&10>i.d.j)))(j={a:c.c,cs:i.Z,cd:i.w,fl:i.ca,je:i.fa,la:i.ga,sw:i.d.k,sh:i.d.j,dm:f.ba,pa:f.ja,pt:f.ua,pr:f.ma,po:f.na,ri:e.D,ru:e.qa,ui:g.id,re:g.ra,vi:g.ya,pv:g.oa,lv:g.ha,vw:E.T,vh:E.R,dw:E.C,
dh:E.A,st:E.N,sl:E.M,tv:"5.0",un:c.b(3),pp:g.ka,cp:g.$,ec:k,aip:c.b(2)?1:n},c.o(11,g.id),a===n&&(j.id=c.id),e.G&&(j.oe=e.G.Aa,j.ok=e.G.Ca),h&&(j.c_n=h.W,j.c_s=h.X,j.c_m=h.V,j.c_c=h.U,j.c_t=h.Y),Z&&(s?(j.o_si=s.K,j.o_vi=s.S,j.o_ci=s.z):c.F=o),d(la(function(a){c.id=a;x(c.g);c.g=w(u(R,c),15E3);A(m,"beforeunload",u(za,c))})),$({I:"pv",H:j}),c.id!==n)?a!==n&&(c.id=n):w(u(Aa,c),500)}function ga(a,b){if("string"==typeof b||"number"==typeof b)b={caption:b};b||(b={});b.gs_evt_name=a;R(this,"event",b)}function R(a,
b,d){if(!a.sa)if(a.id!==n){if(d===n)var c=ja(),d={vw:c.T,vh:c.R,dw:c.C,dh:c.A,st:c.N,sl:c.M};d=d||{};d.a=a.c;d.u=a.b(11);d.i=a.id;d.e=b;d._=C.random();d.tv="5.0";d.et=Ba(a);Z&&(a.F&&s)&&(a.F=p,d.o_si=s.K,d.o_vi=s.S,d.o_ci=s.z);d.cb=la(function(){x(a.g);if(!a.sa)a.g=w(u(R,a),17500+C.random()*5E3)});$({I:"ping",H:d})}else{var f=arguments;w(function(){R.apply({},f)},5E3)}}function ma(){var a=m.olark;a&&a("api.boot.onIdentityReady",function(a,d,c){s={K:a,S:d,z:c}});Z=!!a}function $(a){function b(a){var b=
[],c;for(c in a)a[T](c)&&a[c]!==n&&b.push((S||escape)(c)+"="+(S||escape)(a[c]));return b.join("&")}function d(){e&&f.removeChild(e);e=M;aa=(aa+1)%c[z];$(a)}a.O===n&&(a.O=5);if(--a.O){var c=["data.gosquared.com/"],f=k[da]("head")[0],e=k[ca]("script"),g=p,i=w(d,1E4),h=a.I+"?"+b(a.H);e.src=("https:"==G().s?"https":"http")+"://"+c[aa]+h;e.onload=e.onreadystatechange=function(b){b=this.readyState;if(!g&&(!b||b=="loaded"||b=="complete")){g=o;a.ta&&a.ta();e&&f.removeChild(e);e=M;x(i)}};f.appendChild(e)}}
function la(a){var b="_"+Ca++;P[b]=a;return b}function H(a){function b(){var a=f.name;a&&(f.name=a[t](d)[0])}var d=":_GS_:",c;if(H.L)return H.L;var f=m.top;H.L=c={B:function(){b();f.name=(f.name||"")+d+[a,c.uid,c.n]}};try{var e=f.name||"";if(-1!=e[O](d)){var g=e[t](d)[1][t](",");g[0]==a&&(c.uid=g[1]||"",c.n=g[2]||"")}b()}catch(i){c.B=function(){}}return c}function ua(a,b,d){b=G(G(b).p);return{ja:b.xa+(a.b(7,o)?b.Q:"")[y](/[?&](utm_[^=]*|gclid)=[^&]*/g,"")[y](/^&/,"?")+(a.b(8)?b.wa:""),ua:d!==n?d:
k.title,ba:b.P,ma:b.s,na:b.r||"-",ea:"file:"==b.s,da:/fb_xd_(bust|fragment)/.test(b.p)}}function ya(a){var a=G(a).Q,b,d,c,f;b=/[?&]([^=]+)=([^&]*)/g;d={};for(f=decodeURIComponent;c=b.exec(a[y](/\+/g," "));d[f(c[1])]=f(c[2]));var e;if(a&&(e=d.utm_campaign))return{W:e,X:d.utm_source,V:d.utm_medium,Y:d.utm_term,U:d.utm_content}}function xa(){var a={d:{k:0,j:0},w:"-",ga:(v.language||v.browserLanguage||"-")[N](),fa:+v.javaEnabled(),Z:k.characterSet||k.charSet||"-",ca:function(a,d){var c,f,e,g,i;if(v&&
(c=v.plugins)&&0<(f=c[z]))for(i=0;i<f;i++){if(-1<(g=c[i]).name[O](e=a+" "+d))return c=g.description[t](e+" "),c[1]}else if(c=m.ActiveXObject){try{if(g=(new c((e=a+d+".")+a+d)).GetVariable("$version"))return g=g[t](" ")[1][t](","),g[0]+"."+g[1]+" r"+g[2]}catch(h){}for(i=13;--i;)try{if(g=new c(e+e+i),self.Ba=g&&g.za,g)return i+".0"}catch(k){}}return"-"}("Shockwave","Flash")};L&&(a.d={k:L.width,j:L.height},a.w=L.colorDepth);return a}function ja(){function a(a){return m["inner"+a]||c&&c[f="client"+a]||
d&&d[f]}function b(a){return C.max(d[f="scroll"+a],c[f],d[f="offset"+a],c[f],d[f="client"+a],c[f])}var d=k.body,c=k.documentElement,f;return{T:a("Width"),R:a("Height"),C:b("Width"),A:b("Height"),M:m.pageXOffset||d&&d.scrollLeft||c&&c.scrollLeft||0,N:m.pageYOffset||d&&d.scrollTop||c&&c.scrollTop||0}}function ka(a){x(a.ia);a.ia=w(u(na,a),15E3);a.f||(a.f=o,a.l=+new D)}function na(a){a.f&&(a.f=p,a.h=(a.h||0)+ +new D-a.l)}function Ba(a){var b=a.h,d=+new D;a.f&&(b+=d-a.l,a.l=d);a.h=0;return b}function Aa(a){var b=
u(ka,a);A(k,"mousemove",b);A(k,"keydown",b);A(m,"scroll",b);A(k,"focus",b,"focusin");A(k,"blur",u(na,a),"focusout")}function va(a){var a=a.b(10,k.referrer),b=k.domain,d=p;!a||/^(chrome|about|file):$/.test(a)?a="-":(b=G(a).P[O](b),d=0<=b&&8>=b,a=/^\[.*\]$/.test(a)?"-":a);return{D:+d,qa:a}}function za(a){var b=ia(a);a.b(1)?b.J("gs_p_"+a.c,a.id):(b=H(a.c),b.n=a.id,b.B())}function wa(a,b,d){var c=ia(a,1),f=H(a.c),e=c.m("gs_u_"+a.c)||c.m("gs_u")||f.uid,g=1,i=1,h=(e||"")[t](":"),k,j=o,l=0,Y;!e||!e.match(/^[0-9\:]*$/)?
(j=p,e=0|C.random()*pa):(e=h[0],2>h[z]&&(h[1]=2019,h[2]=4621),4>h[z]&&(h[3]=0),g=(h[1]-2019)/548+ +!!b,i=(h[2]-4621)/379+1,l=h[3]/1E3);c.J("gs_u_"+a.c,f.uid=[e,2019+548*g,4621+379*i,+new D].join(":"));b=c.m("gs_p_"+a.c)||f.n;b!==M&&b!==n&&(Y=b,c.aa("gs_p_"+a.c));d&&(Y=a.id);if((a=a.b(4))&&"object"==typeof a){k=[];for(var m in a)a[T](m)&&k.push(m+"="+("gravatar"==m?Da(a[m][y](/^\s+|\s+$/g,"")[N]()):a[m]));k=k.join("|")}return{id:+e,ya:g,oa:i,ha:~~l,ra:j,ka:Y,$:k}}var I,B=m._gs||(I=o,function(){B.q.push(arguments)});
B.q=B.q||[];if(!B.t){var ra=/^GSN-.*-.$/,q={};if(r){var l,J;for(l in r)J=r[l],"acct"==l?(U(J,"default",o),B("load",function(){function a(a){b[a.shift()].apply(b,a)}var b=r.DefaultTracker=q["default"],d={push:a};if(l=r.q)for(;J=l.shift();)a(J);r.q=d;(l=r.load)&&l(b)})):"load"!=l&&"q"!=l&&B("set",l,J);l=ea.prototype;l.TrackView=X;l.TrackEvent=ga;l.Cancel=function(){this.v()};r.Tracker=U;r.Cancel=u(F,"cancel")}var fa,ha={usecookies:1,anonymiseip:2,visitorname:3,username:3,statuscode:5,cookiedomain:6,
trackparams:7,trackhash:8,trackdelay:9,referrer:10,visitorid:11},Da=function(a){function b(a,b){return((a>>1)+(b>>1)<<1)+(a&1)+(b&1)}for(var d=[],c=0;64>c;)d[c]=0|4294967296*C.abs(C.sin(++c));return function(c){for(var e,g,i,h,k=[],c=unescape(S(c)),j=c[z],m=[e=1732584193,g=-271733879,~e,~g],l=0;l<=j;)k[l>>2]|=(c.charCodeAt(l)||128)<<8*(l++%4);k[c=(j+8>>6)*a+14]=8*j;for(l=0;l<c;l+=a){j=m;for(h=0;64>h;)j=[i=j[3],b(e=j[1],(i=b(b(j[0],[e&(g=j[2])|~e&i,i&e|~i&g,e^g^i,g^(e|~i)][j=h>>4]),b(d[h],k[[h,5*h+
1,3*h+5,7*h][j]%a+l])))<<(j=[7,12,17,22,5,9,14,20,4,11,a,23,6,10,15,21][4*j+h++%4])|i>>>32-j),e,g];for(h=4;h;)m[--h]=b(m[h],j[h])}for(c="";32>h;)c+=(m[h>>3]>>4*(1^h++&7)&15).toString(a);return c}}(16),Z=p,s,aa=0,P={},Ca=0,G=function(a){return function(b,d){b===n&&(b=location.href);a.href=b;d={xa:a.pathname[y](/^([^\/]|$)/,"/$1"),wa:a.hash[y](/^#$/,""),s:a.protocol[y](/^:$/,"")||location.protocol,P:a.hostname||location.hostname,p:a.href,Q:a.search,r:a.port};-1==d.p[O](":"+d.r)&&(d.r="");return d}}(k[ca]("a")),
ba=B.q;m._gs=F;F.t="5.0";for(var K;K=ba.shift();)F.apply({},K);if(I){I=k[da]("script");ba=I[z];K=0;for(var oa;K<ba;)if(oa=I[K++].getAttribute("data-gs")){F(oa);break}}ma();A(m,"load",ma)}})(window.GoSquared,window,document,navigator||{},screen,Math,Date,setTimeout,clearTimeout,encodeURIComponent,1,0,null,2147483647,"createElement","split","replace","length","toLowerCase","hasOwnProperty","getElementsByTagName","indexOf");
