(function(){function y(){}function s(a,b){return 0==ha.call(a).indexOf("[object "+b)}function z(a){return a&&"/"==a.charAt(a.length-1)?a.substr(0,a.length-1):a}function i(a,b){var c,e,d,f;c=1;e=a;b&&(e=e.replace(ia,function(a,b,e,d){e&&c++;f=k;return d||""}));if(f){d=b.split("/");if(c>d)throw Error("attempt to access module beyond root of package: "+a);d.splice(d.length-c,c);return d.concat(e||[]).join("/")}return e}function S(a){var b=a.indexOf("!");return{M:a.substr(b+1),i:0<=b&&a.substr(0,b)}}
function o(){}function t(a,b){o.prototype=a||N;var c=new o;o.prototype=N;for(var e in b)c[e]=b[e];return c}function B(){function a(a,b,d){e.push([a,b,d])}function b(a,b){for(var d,c=0;d=e[c++];)(d=d[a])&&d(b)}var c,e,d;c=this;e=[];d=function(f,c){a=f?function(a){a&&a(c)}:function(a,b){b&&b(c)};d=y;b(f?0:1,c);b=y;e=p};this.t=function(b,d,e){a(b,d,e)};this.f=function(a){c.s=a;d(k,a)};this.d=function(a){c.ga=a;d(w,a)};this.p=function(a){b(2,a)}}function x(a,b,c,e){a instanceof B?a.t(b,c,e):b(a)}function D(a,
b,c){var e;return function(){0<=--a&&b&&(e=b.apply(p,arguments));0==a&&c&&c(e);return e}}function E(){function a(b,d,c,g){var j;j=h.g(m,p,[].concat(b));this.then=b=function(a,b){x(j,function(b){a&&a.apply(p,b)},function(a){if(b)b(a);else throw a;});return this};this.next=function(b,d,e){return new a(b,d,e,j)};d&&b(d,c);x(g,function(){h.h(j)})}var b=[].slice.call(arguments),c;s(b[0],"Object")&&(c=b.shift(),m=h.b(c,m),h.v(c));return new a(b[0],b[1],b[2])}function T(a){var b=a.id;if(b==p)if(F!==p)F=
{C:"Multiple anonymous defines in url"};else if(!(b=h.$()))F=a;if(b!=p){var c=n[b];b in n||(c=h.j(b,m).b,c=n[b]=h.z(c,b));if(!(c instanceof B))throw Error("duplicate define: "+b);c.fa=w;h.A(c,a)}}function ja(a){try{return eval(a)}catch(b){}}function U(){var a;a=u[ka]("link");a.rel="stylesheet";a.type="text/css";return a}function la(a,b,c){V.push({url:a,P:b,S:function(){c(Error(W))}});a=X.shift();!a&&Y.length<ma&&(a=u.createElement("style"),Y.push(a),I.appendChild(a));a&&O(a)}function O(a){var b;(b=
V.shift())?(a.onload=function(){b.P();O(a)},a.onerror=function(){b.S();O(a)},a.styleSheet.addImport(b.url)):(a.onload=a.onerror=C,X.push(a))}function Z(a,b,c){if(!G.load){var e,d,f;if(!a.href||u.readyState&&"complete"!=u.readyState)e=w;else{e=w;try{if(d=a.sheet)f=d.cssRules,e=null===f,!e&&"length"in f&&(d.insertRule("-curl-css-test {}",0),d.deleteRule(0),e=k)}catch(g){e=/security|denied/i.test(g.message)}}e?c():a.onload==C||!a.onload||aa(function(){Z(a,b,c)},b)}}function na(a,b,c,e){function d(){if(f.onload!=
C&&f.onload){f.onload=f.onerror=C;var a=function(){!u.readyState||"complete"==u.readyState?b():aa(a,10)};a()}}var f;f=U();f.onload=function(){G.load=G.load||k;d()};Z(f,e,d);f.onerror=function(){G.error=G.error||k;f.onload!=C&&f.onload&&(f.onload=f.onerror=C,c(Error(W)))};f.href=a;I.appendChild(f)}function C(){}var k=!0,w=!1,v=this.window||global,m,J,P,K=v.document,Q=K&&(K.head||K.getElementsByTagName("head")[0]),oa=Q&&Q.getElementsByTagName("base")[0]||null,ba={},ca={},L={},pa="addEventListener"in
v?{}:{loaded:1,complete:1},N={},ha=N.toString,p,n={},M=w,F,qa=/\?/,da=/^\/|^[^:]+:\/\//,ia=/(\.)(\.?)(?:$|\/([^\.\/]+.*)?)/g,ra=/\/\*[\s\S]*?\*\/|(?:[^\\])\/\/.*?[\n\r]/g,sa=/require\s*\(\s*["']([^"']+)["']\s*\)|(?:[^\\]?)(["'])/g,R,h;h={O:function(a,b){return h.m(i(a,b))},m:function(a,b){return b.c&&a in b.c&&b.c[a].ba||a},n:function(a,b){a&&b.K&&0>a.indexOf("/")&&(a=z(b.K)+"/"+a);return a},g:function(a,b,c,e){function d(b){return h.m(i(b,g.id),a)}function f(b,c,f){var l,ea;l=c&&function(a){c.apply(p,
a)};if(s(b,"String")){b=d(b);f=n[b];ea=f instanceof B&&f.a;if(!(b in n))throw Error("Module not resolved: "+b);if(l)throw Error("require(id, callback) not allowed");return ea||f}x(h.h(h.g(a,g.id,b,e)),l,f)}var g;g=new B;g.id=b||"";g.aa=e;g.B=c;g.b=a;g.q=f;f.toUrl=function(b){return h.j(d(b),a).url};g.O=d;return g},z:function(a,b,c){var e,d,f;e=h.g(a,b,p,c);d=e.f;f=D(1,function(a){e.l=a;try{return h.T(e)}catch(b){e.d(b)}});e.f=function(a){x(c||M,function(){d(n[e.id]=f(a))})};e.D=function(a){x(c||M,
function(){e.a&&(f(a),e.p(ca))})};return e},Q:function(a,b,c,e){return h.g(a,c,p,e)},Z:function(a){return a.q},F:function(a){return a.a||(a.a={})},Y:function(a){var b=a.o;b||(b=a.o={id:a.id,uri:h.G(a),exports:h.F(a),config:function(){return a.b}},b.a=b.exports);return b},G:function(a){return a.url||(a.url=h.w(a.q.toUrl(a.id)),a.b)},b:function(a){var b,c,e,d,f,g;b=!a;a&&(h.b=h.J);a||(a={});e=a.apiName||"curl";d=a.apiContext||v;f=a.defineName||"define";g=a.defineContext||v;c=a.overwriteApi;!b&&J&&(v.curl=
J,J=w);if(!b&&!c&&d[e]&&d[e]!=E)throw Error(e+" already exists");d[e]=E;if(!b||!v.define){if(!b&&!c&&f in g&&g[f]!=P)throw Error(f+" already exists");g[f]=P=function(){var a=h.X(arguments);T(a)};P.amd={plugins:k,jQuery:k,curl:"0.7.0"}}return h.J(a)},J:function(a,b){function c(a,b){var e,c,g,A,j;for(j in a){g=a[j];g.name=g.id||g.name||j;A=d;c=S(z(g.name||j));e=c.M;if(c=h.n(c.i,d))(A=f[c])||(A=f[c]=t(d),A.c=t(d.c),A.e=[]),delete a[j];if(b){c=g;var H=void 0;c.path=z(c.path||c.location||"");H=z(c.main)||
"main";"."!=H.charAt(0)&&(H="./"+H);c.ba=i(H,c.name+"/");c.b=c.config;c.b&&(c.b=t(d,c.b))}else c={path:z(g)};c.N=e.split("/").length;e?(A.c[e]=c,A.e.push(e)):A.u=h.L(g,d)}}function e(a){var b=a.c;a.da=RegExp("^("+a.e.sort(function(a,c){return b[c].N-b[a].N}).join("|").replace(/\/|\./g,"\\$&")+")(?=\\/|$)");delete a.e}var d,f,g;b||(b={});d=t(b,a);d.u=d.baseUrl||"";d.K=d.pluginPath||"curl/plugin";d.R=RegExp(d.dontAddFileExt||qa);d.c=t(b.c);f=a.plugins||{};d.plugins=t(b.plugins);for(g in f)d.plugins[h.n(g,
d)]=f[g];f=d.plugins;d.e=[];c(a.paths,w);c(a.packages,k);for(g in f){f[g]=t(d,f[g]);var j=f[g].e;j&&(f[g].e=j.concat(d.e),e(f[g]))}e(d);return d},v:function(a){var b;(b=a&&a.preloads)&&0<b.length&&x(M,function(){M=h.h(h.g(m,p,b,k))})},j:function(a,b){var c,e,d,f;c=b.c;d=da.test(a)?a:a.replace(b.da,function(a){e=c[a]||{};f=e.b;return e.path||""});return{b:f||m,url:h.L(d,b)}},L:function(a,b){var c=b.u;return c&&!da.test(a)?z(c)+"/"+a:a},w:function(a,b){return a+((b||m).R.test(a)?"":".js")},H:function(a,
b,c){var e=K.createElement("script");e.onload=e.onreadystatechange=function(c){c=c||v.event;if("load"==c.type||pa[e.readyState])delete L[a.id],e.onload=e.onreadystatechange=e.onerror="",b()};e.onerror=function(){c(Error("Syntax or http error: "+a.url))};e.type=a.I||"text/javascript";e.charset="utf-8";e.async=!a.ca;e.src=a.url;L[a.id]=e;Q.insertBefore(e,oa);return e},U:function(a){var b=[],c;("string"==typeof a?a:a.toSource?a.toSource():a.toString()).replace(ra,"").replace(sa,function(a,d,f){f?c=c==
f?p:c:c||b.push(d);return""});return b},X:function(a){var b,c,e,d,f,g;f=a.length;e=a[f-1];d=s(e,"Function")?e.length:-1;2==f?s(a[0],"Array")?c=a[0]:b=a[0]:3==f&&(b=a[0],c=a[1]);!c&&0<d&&(g=k,c=["require","exports","module"].slice(0,d).concat(h.U(e)));return{id:b,l:c||[],r:0<=d?e:function(){return e},k:g}},T:function(a){var b;b=a.r.apply(a.k?a.a:p,a.l);b===p&&a.a&&(b=a.o?a.a=a.o.a:a.a);return b},A:function(a,b){a.r=b.r;a.k=b.k;a.B=b.l;h.h(a)},h:function(a){function b(a,b,c){g[b]=a;c&&r(a,b)}function c(b,
c){var e,d,f,g;e=D(1,function(a){d(a);l(a,c)});d=D(1,function(a){r(a,c)});f=h.V(b,a);(g=f instanceof B&&f.a)&&d(g);x(f,e,a.d,a.a&&function(a){f.a&&(a==ba?d(f.a):a==ca&&e(f.a))})}function e(){a.f(g)}var d,f,g,j,q,r,l;g=[];f=a.B;j=f.length;0==f.length&&e();r=D(j,b,function(){a.D&&a.D(g)});l=D(j,b,e);for(d=0;d<j;d++)q=f[d],q in R?(l(R[q](a),d,k),a.a&&a.p(ba)):q?c(q,d):l(p,d,k);return a},W:function(a){h.G(a);h.H(a,function(){var b=F;F=p;a.fa!==w&&(!b||b.C?a.d(Error(b&&b.C||"define() missing or duplicated: "+
a.url)):h.A(a,b))},a.d);return a},V:function(a,b){var c,e,d,f,g,j,q,r,l,k;c=b.O;e=b.aa;l=b.b||m;d=S(a);j=d.M;f=d.i?h.m(h.n(i(d.i,b.id),l),l):c(j);q=h.j(f,l);if(d.i)g=f;else if(g=q.b.moduleLoader)j=f,f=g,q=h.j(g,l);d=n[f];f in n||(d=n[f]=h.z(q.b,f,e),d.url=h.w(q.url,d.b),h.W(d));f==g&&(r=new B,k=l.plugins[g]||l,x(d,function(a){var b,d,f;f=a.dynamic;j="normalize"in a?a.normalize(j,c,k)||"":c(j);d=g+"!"+j;b=n[d];if(!(d in n)){b=h.Q(k,d,j,e);f||(n[d]=b);var q=function(a){b.f(a);f||(n[d]=a)};q.resolve=
q;q.reject=q.error=b.d;a.load(j,b.q,q,k)}r!=b&&x(b,r.f,r.d,r.p)},r.d));return r||d},$:function(){var a;if(!s(v.opera,"Opera"))for(var b in L)if("interactive"==L[b].readyState){a=b;break}return a}};R={require:h.Z,exports:h.F,module:h.Y};E.version="0.7.0";m=v.curl;"function"==typeof m?(J=m,m=w):v.curl=p;m=h.b(m);h.v(m);n.curl=E;n["curl/_privileged"]={core:h,cache:n,config:function(){return m},_define:T,_curl:E,Promise:B};var fa=this.document;define("curl/plugin/js",["curl/_privileged"],function(a){function b(b,
c,d){function e(){g||(f<new Date?d():setTimeout(e,10))}var f,g,h;f=(new Date).valueOf()+(b.ea||3E5);d&&b.a&&setTimeout(e,10);h=a.core.H(b,function(){g=k;b.a&&(b.s=ja(b.a));!b.a||b.s?c(h):d()},function(a){g=k;d(a)})}function c(a,e){b(a,function(){var b=d.shift();h=0<d.length;b&&c.apply(null,b);e.f(a.s||k)},function(a){e.d(a)})}var e={},d=[],f=fa&&fa.createElement("script").async==k,g,h;g=a.Promise;return{dynamic:k,load:function(a,r,l,i){function p(a){(l.error||function(a){throw a;})(a)}var m,n,t,u,
o;m=0<a.indexOf("!order");n=a.indexOf("!exports=");t=0<n&&a.substr(n+9);u="prefetch"in i?i.prefetch:k;a=m||0<n?a.substr(0,a.indexOf("!")):a;o=r.toUrl(a.lastIndexOf(".")<=a.lastIndexOf("/")?a+".js":a);o in e?e[o]instanceof g?e[o].t(l,p):l(e[o]):(a={name:a,url:o,ca:m,a:t,ea:i.timeout},e[o]=r=new g,r.t(function(a){e[o]=a;l(a)},p),m&&!f&&h?(d.push([a,r]),u&&(a.I="text/cache",b(a,function(a){a&&a.parentNode.removeChild(a)},function(){}),a.I="")):(h=h||m,c(a,r)))}}});var ka="createElement",aa=this.setTimeout,
u=this.document,I,ta=u&&u.createStyleSheet&&!(10<=u.documentMode),Y=[],X=[],V=[],ma=12,ga,W="HTTP or network error.",G={};u&&(I=u.head||u.getElementsByTagName("head")[0],ga=ta?la:na);define("curl/plugin/css",{normalize:function(a,b){var c,e;if(!a)return a;c=a.split(",");e=[];for(var d=0,f=c.length;d<f;d++)e.push(b(c[d]));return e.join(",")},load:function(a,b,c,e){function d(){0==--i&&c()}function f(a){(c.d||function(a){throw a;})(a)}var g,h,i,k;g=(a||"").split(",");h=e.cssWatchPeriod||50;e=e.cssNoWait;
i=g.length;for(k=0;k<g.length;k++){var a=g[k],l,a=b.toUrl(a.lastIndexOf(".")<=a.lastIndexOf("/")?a+".css":a);e?(l=U(),l.href=a,I.appendChild(l),d()):ga(a,d,f,h)}},"plugin-builder":"./builder/css",pluginBuilder:"./builder/css"})}).call(this);
(function(y){var s=function(i){for(var s={},i=i.substr(1).split("&"),o=i.length-1;o>=0;o--){var t=i[o].split("=");s[t[0]]=decodeURIComponent((t[1]||"").replace(/\+/g,"%20"))}return s}(location.search);if(s.n_s)document.documentElement.className+=" not-supported type-"+s.n_s;else{y.jsonData=function(){var i=document.getElementById("disqus-jsonData");return i.textContent||i.innerHTML}();var z=function(){var i=[],s=!1;if(DISQUS.config&&DISQUS.config.switches)for(var o=0,t=DISQUS.config.switches.length;o<
t;o++)if(DISQUS.config.switches[o]=="next_use_jquery"){s=!0;break}s||y.name.indexOf("hiro_fixture")>-1?i.push("js!build/next/lib.js!order"):i.push("js!build/next/lib.ender.js!order");i.push("js!build/next/lounge/client.js!order");i.push("css!build/next/styles/lounge.css");i.push("js!build/next/templates/lounge.js!order");curl(i).then(function(){var i=JSON.parse(y.jsonData);i.code?($("#postCompatContainer").hide(),$("#error").show(),DISQUS.Bus.sendHostMessage("fail",i)):(new DISQUS.next.views.Lounge({jsonData:i}),
DISQUS.next.lounge.tracking.init(DISQUS.next.views.Lounge.getInstance()))})};y.onload=function(){curl({baseUrl:y.location.protocol=="https:"?"https://securecdn.disqus.com/1374098100":"http://mediacdn.disqus.com/1374098100"});curl(["js!/next/config.js?forum="+s.f+"!order"]).then(z)}}})(window);